#!/bin/sh

# create input file from 1D computation for funkySetFields
mkdir 1d_profil
cp -r ../1DMuIChangedDomain/400 ./1D/
cp -r ../1DMuIChangedDomain/constant/polyMesh/* ./1D/constant/polyMesh

# use 1D results for BC and IC
python3 -c "import fluidfoam; fluidfoam.create1dprofil('1D', '.', '400', 'Y', ['Ua', 'Ub', 'alpha_a', 'muI', 'p_rbgh', 'pa'])"

# create the mesh
blockMesh

# create the intial time folder
cp -r 0_org 0

# Initialize the alpha, muI, p*, U* field
# start from dry bed
funkySetFields -time 0

# save log file size
sedFoam_rbgh | tail -300 > log